### PR TITLE
Rename README.markdown to README.md

### PR DESCRIPTION
**Pull request by SUPERCILEX**

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Hello. Could you elaborate on the rationale for this PR?

**Comment by SUPERCILEX** [comment]
`.markdown` is no longer necessary and looks funky. See [CONTRIBUTING.md](https://github.com/travis-ci/travis-ci/blob/master/CONTRIBUTING.md) for example.

**Comment by andrewda** [comment]
Yes, it does seem a bit weird to have a `.markdown` file _and_ a `.md` file. This gets my +1.

**Comment by Monkeyboy2805** [comment]
Look good to me.

**Comment by BanzaiMan** [comment]
Not sure why I'd locked this. Sorry. If you redo the renaming, I can merge this.

**Comment by SUPERCILEX** [comment]
@BanzaiMan Sweet! 😄 I deleted the repo since then so I can't update this PR, but I've created a [new one](https://github.com/travis-ci/travis-ci/pull/8256).

**Pull request closed without merging**
