### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by iammosespaulr**

### CODE REVIEW

**Comment by BanzaiMan** [comment]
There is no code in this repository for any pull request.

**Comment by Nenglish7** [comment]
I agree no pull request template is needed.

**Comment by Monkeyboy2805** [comment]
Erm... This repo is kind of only used for issues at the minute.

**Comment by Monkeyboy2805** [comment]
Although it could be used on other repositories that are used for actual code, it looks alright for that purpose

**Pull request closed without merging**
